//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Addons.ReferenceGridFormWorkSpaceEditorAddon.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Addons.ReferenceGridFormWorkSpaceEditorAddon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap addon {
            get {
                object obj = ResourceManager.GetObject("addon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Save new work area... 的本地化字符串。
        /// </summary>
        internal static string Button_CreateWorkSpace {
            get {
                return ResourceManager.GetString("Button_CreateWorkSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage work areas... 的本地化字符串。
        /// </summary>
        internal static string Button_EditWorkSpaces {
            get {
                return ResourceManager.GetString("Button_EditWorkSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Work areas 的本地化字符串。
        /// </summary>
        internal static string Menu_Caption {
            get {
                return ResourceManager.GetString("Menu_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string NameEditor_Button_Cancel {
            get {
                return ResourceManager.GetString("NameEditor_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string NameEditor_Button_Create {
            get {
                return ResourceManager.GetString("NameEditor_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        internal static string NameEditor_Button_Rename {
            get {
                return ResourceManager.GetString("NameEditor_Button_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work area name 的本地化字符串。
        /// </summary>
        internal static string NameEditor_Form_Text {
            get {
                return ResourceManager.GetString("NameEditor_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work area name: 的本地化字符串。
        /// </summary>
        internal static string NameEditor_Label_Name {
            get {
                return ResourceManager.GetString("NameEditor_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string WorkSpaceEditor_Button_Close {
            get {
                return ResourceManager.GetString("WorkSpaceEditor_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save new work area... 的本地化字符串。
        /// </summary>
        internal static string WorkSpaceEditor_Button_ToolTip_Add {
            get {
                return ResourceManager.GetString("WorkSpaceEditor_Button_ToolTip_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete work area 的本地化字符串。
        /// </summary>
        internal static string WorkSpaceEditor_Button_ToolTip_Remove {
            get {
                return ResourceManager.GetString("WorkSpaceEditor_Button_ToolTip_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage work areas 的本地化字符串。
        /// </summary>
        internal static string WorkSpaceEditor_Form_Text {
            get {
                return ResourceManager.GetString("WorkSpaceEditor_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to delete &quot;{0}&quot;? 的本地化字符串。
        /// </summary>
        internal static string WorkSpaceEditor_Messages_RemoveWorkSpace {
            get {
                return ResourceManager.GetString("WorkSpaceEditor_Messages_RemoveWorkSpace", resourceCulture);
            }
        }
    }
}
