//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Addons.MacroManagerAddon.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Addons.MacroManagerAddon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap addon {
            get {
                object obj = ResourceManager.GetObject("addon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        internal static string Btn_Ok {
            get {
                return ResourceManager.GetString("Btn_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Under Configure, select the folder in which the macros should be saved. 的本地化字符串。
        /// </summary>
        internal static string ConfigurateAddonMessage {
            get {
                return ResourceManager.GetString("ConfigurateAddonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure 的本地化字符串。
        /// </summary>
        internal static string ConfigurateCommand {
            get {
                return ResourceManager.GetString("ConfigurateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration of the environment variable or path 的本地化字符串。
        /// </summary>
        internal static string DirectoryDialogTitle {
            get {
                return ResourceManager.GetString("DirectoryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The folder with the macros was not found. Please configure it again. 的本地化字符串。
        /// </summary>
        internal static string DirectoryNotFoundMessage {
            get {
                return ResourceManager.GetString("DirectoryNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The folder &apos;{0}&apos; was not found. Please choose another one. 的本地化字符串。
        /// </summary>
        internal static string DirectoryNotResolveMessage {
            get {
                return ResourceManager.GetString("DirectoryNotResolveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string EditCommand {
            get {
                return ResourceManager.GetString("EditCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No environment variables for the user were found with a valid path. 的本地化字符串。
        /// </summary>
        internal static string EnvironmentVariablesNotFound {
            get {
                return ResourceManager.GetString("EnvironmentVariablesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the folder in which the macros should be saved. 的本地化字符串。
        /// </summary>
        internal static string FolderBrowseDialogDescription {
            get {
                return ResourceManager.GetString("FolderBrowseDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Macro {
            get {
                object obj = ResourceManager.GetObject("Macro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Macros 的本地化字符串。
        /// </summary>
        internal static string MacroCommand {
            get {
                return ResourceManager.GetString("MacroCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Macro Editor… 的本地化字符串。
        /// </summary>
        internal static string MacroEditorCommand {
            get {
                return ResourceManager.GetString("MacroEditorCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap maschine {
            get {
                object obj = ResourceManager.GetObject("maschine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Open folder in Windows Explorer 的本地化字符串。
        /// </summary>
        internal static string OpenInExplorerCommand {
            get {
                return ResourceManager.GetString("OpenInExplorerCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It&apos;s possible to use environment variables for the path &apos;{0}&apos;. 
        ///
        ///&apos;{1}&apos;
        ///
        ///Do you want to use an environment variable instead of the absolute path? 的本地化字符串。
        /// </summary>
        internal static string PathAsVariableMessage {
            get {
                return ResourceManager.GetString("PathAsVariableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path &apos;{0}&apos; was not found. The display was updated. 的本地化字符串。
        /// </summary>
        internal static string PathNotFoundMessage {
            get {
                return ResourceManager.GetString("PathNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string RefreshCommand {
            get {
                return ResourceManager.GetString("RefreshCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        internal static string RunCommand {
            get {
                return ResourceManager.GetString("RunCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 There are elements in the Macro Editor that have not been saved. Do you want to save them before running the command? 的本地化字符串。
        /// </summary>
        internal static string UserWarningSaveMessage {
            get {
                return ResourceManager.GetString("UserWarningSaveMessage", resourceCulture);
            }
        }
    }
}
